import './globals.css'
import { Inter } from 'next/font/google'
import Form from './component/form'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sign Up',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Form />
        {children}</body>
    </html>
  )
}
